// Books listing store
export const BOOKS_LIST_ERROR = 'BOOKS_LIST_ERROR'
export const BOOKS_LIST_LOADING = 'BOOKS_LIST_LOADING'
export const BOOKS_LIST_SUCCESS = 'BOOKS_LIST_SUCCESS'
export const BOOKS_FILTER_RESULTS = 'BOOKS_FILTER_RESULTS'

// Book store
export const BOOK_SHOW_ERROR = 'BOOK_SHOW_ERROR'
export const BOOK_SHOW_LOADING = 'BOOK_SHOW_LOADING'
export const BOOK_SHOW_SUCCESS = 'BOOK_SHOW_SUCCESS'
export const BOOK_SHOW_RESET = 'BOOK_SHOW_REST'
export const BOOK_PRELOAD_SUCCESS = 'BOOK_PRELOAD_SUCCESS'
